### ISSUE TITLE
Trouble Booting 1.0.0

### ISSUE THREAD

**Issue by meawoppl** [heronarts/Chromatik#1]
Hey @mcslee !

Working on a project with some nerds I love (slow learner). I was trying to get the new version of Chromatik working for some LED controls, but I am hitting an init glitch that I don't really know how to triage:

```
/home/meawoppl/.gradle/jdks/eclipse_adoptium-17-amd64-linux.2/bin/java -Dfile.encoding=UTF-8 -jar /home/meawoppl/repos/tentacles/lib/chromatik-1.0.0-linux-x64.jar
[Chromatik 2024/11/09 20:21:29] Starting Chromatik version 1.0.0
[Chromatik 2024/11/09 20:21:29] Running java 17.0.13 Eclipse Adoptium Linux 6.5.0-44-generic amd64
[Chromatik 2024/11/09 20:21:29] No Chromatik license present, features will be limited.
[GLX 2024/11/09 20:21:30] GLX monitorWorkarea: size(1920x1048), pos(x:1920,y:32)
[GLX 2024/11/09 20:21:30] GLX createWindow: 1280x720
[GLX 2024/11/09 20:21:30] GLX systemContentScale: 1.0x1.0
[GLX 2024/11/09 20:21:30] GLX windowSize: 1280x720
[GLX 2024/11/09 20:21:30] GLX framebufferSize: 1280x720
[GLX 2024/11/09 20:21:30] GLX uiSize: 1280.0x720.0
[GLX 2024/11/09 20:21:30] GLX cursorScale: 1.0x1.0
[GLX 2024/11/09 20:21:30] Using BGFX renderer: Vulkan
[Chromatik 2024/11/09 20:21:30] Unhandled exception in Chromatik.main: java.io.IOException: No shaders supported for Vulkan renderer
java.lang.RuntimeException: java.io.IOException: No shaders supported for Vulkan renderer
	at heronarts.glx.shader.Tex2d.<init>(Tex2d.java:100)
	at heronarts.glx.GLX$Programs.<init>(GLX.java:119)
	at heronarts.glx.GLX.<init>(GLX.java:175)
	at heronarts.lx.studio.LXStudio.<init>(LXStudio.java:143)
	at heronarts.lx.studio.LXStudio.<init>(LXStudio.java:139)
	at heronarts.lx.studio.Chromatik.<init>(Chromatik.java:45)
	at heronarts.lx.studio.Chromatik.main(Chromatik.java:319)
Caused by: java.io.IOException: No shaders supported for Vulkan renderer
	at heronarts.glx.GLXUtils.loadShader(GLXUtils.java:132)
	at heronarts.glx.shader.Tex2d.<init>(Tex2d.java:92)
	... 6 more
```

I'm on pretty vanilla ubuntu (23.10) using the reccomended Java. Lmk

**Comment by zellers** [comment]
Based on [similar conversations](https://discord.com/channels/1132946397382062090/1274978985138323509/1275084142727401545) on the Chromatik Discord I believe UI on Linux is currently unavailable:

> Yeah this is a known issue, I have a flag to force OpenGL mode but I believe the window transformations are not set up properly for the NDC on Linux so stuff is ending up invisible or out-of-window. 

The OpenGL flag might be `--opengl` based [on this post](https://discord.com/channels/1132946397382062090/1132946399537926188/1274925847597551699) but YMMV. `--headless` is the other option on Linux ;-)

**Comment by mcslee** [comment]
Yes, sorry about this. Confirming that full Linux UI doesn't work properly at the moment. If you pass the `--opengl` flag typcially the 2D UI will work fine but the 3D preview window doesn't have its transformations set up properly for OpenGL on Linux.

It's on my radar but I don't have a Linux desktop machine set up to work on, so I need to round one up at some point.

Here is where the issue likely is:
https://github.com/heronarts/GLX/blob/dev/src/main/java/heronarts/glx/View.java#L161

You can see how `setScreenOrtho` has special casing, calling `setOrtho` vs. `setOrthoLH` depending upon the framework. This is what the `UI2dContext` graphics use, and as such that all works fine.

The `UI3dContext` graphics, however, use the projections in either [`setPerspective`](https://github.com/heronarts/GLX/blob/dev/src/main/java/heronarts/glx/View.java#L151) or [`setOrthographic`](https://github.com/heronarts/GLX/blob/dev/src/main/java/heronarts/glx/View.java#L145). Those don't have special casing, they're always using LH (left-handed) variants, but they'll need to be special cased to use the default right-handed versions for OpenGL. `setCamera` may also need this special casing. If you feel comfortable diving in and rebuilding the GLX library for your build, that's where the changes will live.

**Comment by meawoppl** [comment]
Ick! I don't think I am skillful enough to swing this tbh. 

I can offer Linux desktop access if that is helpful

**Comment by meawoppl** [comment]
Also confirming the `--opengl` flag lets it boot, but nothing renders in the central window.

**Comment by mcslee** [comment]
> I can offer Linux desktop access if that is helpful

Issue is laziness not availability... finally pulled the RPi 400 out of the closet, found the wacky mini-HDMI cable and all that.

I think I've fixed this. The key change was some positioning nonsense:
https://github.com/heronarts/GLX/commit/c09df75bd4dad3ea4b12232c642cbb23f6f191c5

I've also hardcoded the use of OpenGL when Linux is detected as the platform, since Vulkan is never going to work at the moment.

Until the next release, pre-release builds are available here:
https://chromatik.co/linux/

That links here (tho may be changed if I need to do more update):
https://github.com/heronarts/Chromatik/releases/tag/1.0.1-SNAPSHOT-2024-11-11

Closing this for now as I believe this resolves the issue, but please do let me know if it works for you, and definitely re-open if you still have issues.
